name: Build Python Package

on:
  workflow_call:
    outputs:
      package-built:
        description: "Whether the package was successfully built"
        value: ${{ jobs.build.outputs.package-built }}

jobs:
  build:
    name: Build Python distribution packages
    runs-on: ubuntu-latest
    outputs:
      package-built: ${{ steps.build.outputs.package-built }}

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up uv
        uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
        with:
          version: ">=0.9.12"
          enable-cache: true

      - name: Set up Python environment (.python-version)
        run: uv python install

      - name: Configure Git for tests
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Build distribution packages
        id: build
        run: |
          # uv build
          if uv run poe build; then
            echo "package-built=true" >> "$GITHUB_OUTPUT"
          else
            echo "package-built=false" >> "$GITHUB_OUTPUT"
            exit 1
          fi

      # # Verify that the built packages work correctly
      # - name: Test wheel installation
      #   run: uv run --isolated --no-project --with dist/*.whl h4-hello

      # - name: Test source distribution installation
      #   run: uv run --isolated --no-project --with dist/*.tar.gz h4-hello

      - name: Upload built packages as artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: python-package-distributions
          path: dist/
          retention-days: 1
